### ISSUE TITLE
error: redefinition of module 'Setapp'

### ISSUE THREAD

**Issue by marcuseckert** [johnno1962/InjectionNext#7]
Hey,
love the plugin, thanks for all your hard work!
I've been trying the new version (XCode 15.4, iPhone 14 Pro Sim), it's making the connection to the sim but when I save sth it gives me:

`🔥 ⚠️ Recompile failed for: /Users/marcus/Documents/FF/Rivulet/App/Rivulet/ViewControllers/MainMenuViewController.swift
/Users/marcus/Library/Developer/Xcode/DerivedData/Rivulet-ftszssuouwmthpfjxrvfecwktczw/Build/Products/Debug-iphonesimulator/include/module.modulemap:1:8: error: redefinition of module 'Setapp'
module Setapp {
       ^
/Users/marcus/Library/Developer/Xcode/DerivedData/Rivulet-ftszssuouwmthpfjxrvfecwktczw/Index.noindex/Build/Products/Debug-iphonesimulator/include/module.modulemap:1:8: note: previously defined here
module Setapp {`

Setapp is the framework for the app to run in an alt appstore. You can find the source here: https://github.com/MacPaw/Setapp-framework/tree/beta/setapp-mobile.

Any idea what might be up?

**Comment by johnno1962** [comment]
Hi, I've pushed a commit to branch `single-include` on the repo if you'd like to build the InjectionNext.app off that branch and give it a try. It's the only thing I could think of at this stage.

**Comment by johnno1962** [comment]
I've been able to replicate and resolve the issue you were seeing and have pushed a new 1.1.2 version of the app.

**Comment by marcuseckert** [comment]
thanks for looking into this so quickly! I just had a chance to check it out and unfortunately I'm still seeing the bug.
`/Users/marcus/Library/Developer/Xcode/DerivedData/Rivulet-ftszssuouwmthpfjxrvfecwktczw/Index.noindex/Build/Products/Debug-iphonesimulator/include/module.modulemap:1:8: error: redefinition of module 'Setapp'
module Setapp {
       ^
/Users/marcus/Library/Developer/Xcode/DerivedData/Rivulet-ftszssuouwmthpfjxrvfecwktczw/Build/Products/Debug-iphonesimulator/include/module.modulemap:1:8: note: previously defined here
module Setapp {
       ^
/Users/marcus/Library/Developer/Xcode/DerivedData/Rivulet-ftszssuouwmthpfjxrvfecwktczw/Index.noindex/Build/Products/Debug-iphonesimulator/include/module.modulemap:8:15: error: redefinition of module 'Swift'
module Setapp.Swift {
              ^
/Users/marcus/Library/Developer/Xcode/DerivedData/Rivulet-ftszssuouwmthpfjxrvfecwktczw/Build/Products/Debug-iphonesimulator/include/module.modulemap:8:15: note: previously defined here
module Setapp.Swift {`
I used the version you pushed yesterday and didn't build from that branch. Let me know if there's anything else I could try or do to help!

**Comment by johnno1962** [comment]
What file and target of your project are you trying to Inject?

**Comment by johnno1962** [comment]
I've pushed a new branch `other-includes` if you'd like to build the app and try it out for me.

**Comment by johnno1962** [comment]
I've pushed another less conservative commit to that branch if you want to build the app and try it out.

**Comment by johnno1962** [comment]
Great! There had to be a solution. I'm still tidying things up and performing more testing and will merge and build a new release later on. Thanks for raising this issue and testing the various iterations.

**Comment by marcuseckert** [comment]
well, my thanks to you! this is what apple should really be doing:)

**Comment by johnno1962** [comment]
Tell me about it. I've pushed a 1.1.3 release if you want to check it out for me.

**Comment by marcuseckert** [comment]
The latest release works also!
